

#storage INTEGRATION

CREATE OR REPLACE STORAGE INTEGRATION MY_DATA_INTEGRATION
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::123456789012:role/snowflake_s3_access_role'
  STORAGE_ALLOWED_LOCATIONS = ('s3://my-enterprise-data-bucket/');


#stage creation
CREATE OR REPLACE STAGE MY_DATABASE.MY_BRONZE_SCHEMA.DBT_STAGE 
  STORAGE_INTEGRATION = MY_DATA_INTEGRATION 
  URL = 's3://my-enterprise-data-bucket/raw/' 
  FILE_FORMAT = (TYPE = 'CSV' FIELD_DELIMITER = ',' SKIP_HEADER = 1);
